apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-config
data:
  DATABASE_URL: "jdbc:postgresql://200.23.25.23:5432/curso"
  DATABASE_USERNAME: "curso"
  SERVER_PORT: "8080"
  LOGSTASH_SERVER: "10.23.25.26:5000"
  JAVA_OPTS: "-Xms200m -Xmx512m"
