
services:
  ms-factura:
    image: mauron/ms-factura:3
    container_name: ms-factura-01
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/demo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456
      - SERVER_PORT=8080
      - LOGSTASH_SERVER=logstash:5000
      - JAVA_OPTS=-Xms200m -Xmx256m
    ports:
      - "9091:8080"
    networks:
      - curso
      - elk_elk
    restart: always

networks:
  curso:
    external: true
  elk_elk:
    external: true