
services:
  ms-factura:
    image: mauron/ms-factura:3
    container_name: ms-factura-02
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/demo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123456
      - SERVER_PORT=8081
      - LOGSTASH_SERVER=logstash:5000
    ports:
      - "9091:8081"
    networks:
      - curso
      - elk_elk
    restart: always
  

  postgres:
    image: postgres:latest
    container_name: postgres-02
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=demo
    ports:
      - "5433:5432"
    networks:
      - curso
    restart: always

    # add eLK stack

networks:
  curso:
    external: true
  elk_elk:
    external: true